steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/peppy-archive-464519-f3/frontend-image', '-f', 'frontend/Dockerfile', 'frontend/']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/peppy-archive-464519-f3/frontend-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'frontend-service',  # Replace with your desired service name
      '--image', 'gcr.io/peppy-archive-464519-f3/frontend-image',
      '--platform', 'managed',
      '--region', 'us-east4',  # Change to a different region
      '--allow-unauthenticated'  # Optional: Remove if you want to restrict access
    ]

options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only
